# stable/prometheus-operator values 修改

alertmanager:
  enabled: true
  service:
    nodePort: 30903
    type: NodePort
  alertmanagerSpec:
    replicas: 1

grafana:
  enabled: true
  adminPassword: admin

prometheus:
  enabled: true
  service:
    nodePort: 30090
    type: NodePort
  prometheusSpec:
    replicas: 1
    storageSpec:
      volumeClaimTemplate:
        spec:
          selector:
            matchLabels:
              app: prometheus-pv
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
    securityContext:
      fsGroup: 0
      runAsNonRoot: false
      runAsUser: 0
    additionalScrapeConfigs:
      - job_name: kubernetes-service-endpoints
        kubernetes_sd_configs:
        - role: endpoints
        relabel_configs:
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
          action: replace
          target_label: __scheme__
          regex: (https?)
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
          action: replace
          target_label: __address__
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: "\$1:\$2"
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_service_name]
          action: replace
          target_label: kubernetes_name