apiVersion: v1
kind: Service
metadata:
  name: etcd-k8s
  namespace: kube-system
  labels:
    k8s-app: etcd
spec:
  type: ClusterIP
  clusterIP: None  # 一定要设置 clusterIP:None
  ports:
    - name: port
      port: 2381
---
apiVersion: v1
kind: Endpoints
metadata:
  name: etcd-k8s
  namespace: kube-system
  labels:
    k8s-app: etcd
subsets:
  - addresses:
      - ip: 192.168.50.100  # 指定etcd节点地址，如果是集群则继续向下添加; 需要修改静态pod的参数127.0.0.1:2381 ==> 0.0.0.0:2381
        nodeName: etc-master
    ports:
      - name: port
        port: 2381