# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "k8s-centos/7"

    config.vm.box_check_update = false
    config.vm.synced_folder "./config", "/vagrant", type: "rsync"

    config.ssh.username = 'root'
    config.ssh.password = 'vagrant'
    config.ssh.insert_key = 'true'

    config.vm.hostname = 'testCentos7'

    config.vm.provider "virtualbox" do |vb|
       vb.name = "testCentos7"
       vb.gui = false
    end
end
