# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.synced_folder "../scripts", "/vagrant", type: "rsync"

  config.vm.define "k8s-master" do |node|
    node.vm.box = "myCentos7"
    node.vm.hostname = "k8s-master"
    node.vm.network "private_network", ip: "192.168.50.100"

    node.vm.provider "virtualbox" do |vb|
      vb.name = "k8s-master"
      vb.gui = false
      vb.memory = 8192
      vb.cpus = 2
    end

    node.vm.provision "shell", path: "init-node.sh"
  end
  
end
