apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-jenkins
  labels:
    app: local-pv-jenkins
spec:
  capacity:
    storage: 8Gi
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-jenkins
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /data/jenkins2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-master