# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "myCentos7"

    config.vm.network "private_network", ip: "192.168.56.100"

    config.vm.synced_folder "../yum", "/vagrant", type: "rsync"

    config.vm.provider "virtualbox" do |vb|
       vb.name = "testCentos7"
       vb.gui = false
    end
end
